[build]
  base = "./"
  publish = "./build"
  command = "yarn build"

[template.environment]
  REACT_APP_PROD = "https://trainingbot-3.herokuapp.com"
  REACT_APP_API = "https://trainingbot3.netlify.com/callback"
  NODE_PATH = "src/"

# Redirect all requests to our domain to our client-side router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200