[build]
  base = "./"
  publish = "./build"
  command = "yarn build"

[template.environment]
  REACT_APP_PROD = "trainingbot3.auth0.com"
  REACT_APP_API = "https://www.trainingbot3.netlify.com/"
  NODE_PATH = "src/"

# Redirect all requests to our domain to our client-side router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200