[build]
  base = "./"
  publish = "./build"
  command = "yarn build"

[template.environment]
  REACT_APP_PROD = "Your Auth0 Callback URL (no trailing slash)"
  REACT_APP_API = "Your production API url (no trailing slash)"
  NODE_PATH = "Your NODE_PATH (src/)"

# Redirect all requests to our domain to our client-side router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200